baseURL = "https://mate.sysadmon.de/"
languageCode = "de-de"
title = "fussel.space"
theme = "fussel.theme"
enableGitInfo = false

[params]
  description = "A small website. About mate. And foo. Originally created by bake"

[permalinks]
  mate = "/mate/:slug/"

[outputs]
  page = ["html", "json"]
  section = ["html", "json"]

[menu]
  [[menu.meta]]
    identifier = "start"
    name = "Start"
    url = "/"
    weight = 10
  [[menu.meta]]
    identifier = "api"
    name = "API"
    url = "/mate/index.json"
    weight = 20
